### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JayZangwill** [sabrinaluo/sabrinaluo.github.io#2]
我很好奇：为何把sabrinaluo.github.io输入到网址栏上会自动跳到http://sabrinaluo.com/
，我想问问你怎么实现的。
另外赞一个，做得非常好，嘻嘻！

**Comment by sabrinaluo** [comment]
CNAME
具体可以看 http://sabrinaluo.com/tech/2015/12/13/set-a-custom-domain-for-github-page/
